# --- backend/app/services/user_service.py ---
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from app.models import user as user_models # Pydantic schemas (use alias if needed)
# --- >>> THIS IS THE CORRECTED LINE <<< ---
from app.models.user import User as UserModel      # Import SQLAlchemy User model from models/user.py
# --- >>> END CORRECTION <<< ---
import datetime
import logging
from typing import Optional, List, Dict, Any

logger = logging.getLogger(__name__)

async def get_user_by_provider_id(db: AsyncSession, *, provider: str, provider_id: str) -> Optional[UserModel]:
    """Finds a user by their OAuth provider and provider-specific ID."""
    logger.info(f"Querying user by provider={provider}, provider_id={provider_id[:5]}...")
    statement = select(UserModel).where(UserModel.provider == provider, UserModel.provider_id == provider_id)
    result = await db.execute(statement)
    user = result.scalar_one_or_none()
    if user:
        # Update last login time on fetch
        user.last_login = datetime.datetime.now(datetime.timezone.utc)
        await db.commit()
        await db.refresh(user)
        logger.info(f"User found for provider={provider}, provider_id={provider_id[:5]}...")
    else:
        logger.info(f"User NOT found for provider={provider}, provider_id={provider_id[:5]}...")
    return user

async def create_user(db: AsyncSession, *, user_in: user_models.UserCreate) -> UserModel:
    """Creates a new user in the database."""
    logger.info(f"Creating new user for provider={user_in.provider}, email={user_in.email}")
    db_user = UserModel(
        provider=user_in.provider,
        provider_id=user_in.provider_id,
        email=str(user_in.email) if user_in.email else None, # Ensure email is string or None
        display_name=user_in.display_name,
        profile_picture_url=str(user_in.profile_picture_url) if user_in.profile_picture_url else None # Ensure URL is string or None
        # created_at and last_login have defaults
    )
    db.add(db_user)
    await db.commit() # Commit to get the ID generated by DB
    await db.refresh(db_user) # Refresh to load default values like ID, created_at
    logger.info(f"User created successfully with ID: {db_user.id}")
    return db_user

async def get_or_create_user(db: AsyncSession, *, user_data: user_models.UserUpsertData) -> UserModel:
    """Gets a user by provider ID or creates them if they don't exist."""
    logger.info(f"Getting or creating user: provider={user_data.provider}, provider_id={user_data.provider_id[:5]}...")
    db_user = await get_user_by_provider_id(db=db, provider=user_data.provider, provider_id=user_data.provider_id)
    if db_user:
        # Optionally update display name or picture URL if changed
        if db_user.display_name != user_data.display_name or \
           db_user.profile_picture_url != (str(user_data.profile_picture_url) if user_data.profile_picture_url else None):
            logger.info(f"Updating profile data for existing user {db_user.id}")
            db_user.display_name = user_data.display_name
            db_user.profile_picture_url = str(user_data.profile_picture_url) if user_data.profile_picture_url else None
            await db.commit()
            await db.refresh(db_user)
        return db_user
    else:
        # Create user if not found
        user_create_schema = user_models.UserCreate(**user_data.model_dump())
        return await create_user(db=db, user_in=user_create_schema)

async def get_user_by_id(db: AsyncSession, user_id: int) -> Optional[UserModel]:
    """Finds a user by their internal database ID."""
    logger.info(f"Querying user by internal ID: {user_id}")
    statement = select(UserModel).where(UserModel.id == user_id)
    result = await db.execute(statement)
    user = result.scalar_one_or_none()
    if user: logger.info(f"User found for ID {user_id}")
    else: logger.info(f"User NOT found for ID {user_id}")
    return user